### ISSUE TITLE
Error reading rasp.json: Expecting property name enclosed in double quotes: line 73 column 9 (char 2069)

### ISSUE THREAD

**Issue by RKeertishKumar** [rbidou/pyrasp#2]
![image](https://github.com/rbidou/pyrasp/assets/141417594/46d97ef2-bb8a-4999-8432-d96c2074b2a7)
So, the line trying to indicate cloud operations is causing a reading error cause json expects all values in data or key value format. So, 
please remove the line.

If you really want to add a comment line, you can add a comment based key value pair that we won't use. You can refer the link below for what I mean.

https://gist.github.com/MoOx/5271067

**Comment by rbidou** [comment]
Fixed
