### ISSUE TITLE
Handle XSS payloads via file uploads (.pdf, .svg, etc.)

### ISSUE THREAD

**Issue by ayusshsoarav** [rbidou/pyrasp#5]
Hi @rbidou 

This is a feature/enhancement request.

PyRASP should detect XSS payloads inside PDF, SVG files that are uploaded to the application or to cloud via the application.
In case a malicious payload is detected, the file upload should be stopped.

Thanks

**Comment by rbidou** [comment]
After first tests, such feature would generate too much false positive with the current engine.
It would require accurate identification of file type and full parsing of the content prior to security analysis. It would also be misleading if only XSS payloads are detected, giving a fake sense of security when a malicious file (such as malware) could be uploaded.
Consequently, it is not planned to develop such feature at short term (at least not for v1.0).
